/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ApiPublicWebhooksCheckoutRouteImport } from './routes/api/public/webhooks/checkout'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCheckoutRoute =
  ApiPublicWebhooksCheckoutRouteImport.update({
    id: '/api/public/webhooks/checkout',
    path: '/api/public/webhooks/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/verify': typeof VerifyRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/webhooks/checkout': typeof ApiPublicWebhooksCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/verify': typeof VerifyRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/webhooks/checkout': typeof ApiPublicWebhooksCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/verify': typeof VerifyRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/webhooks/checkout': typeof ApiPublicWebhooksCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/verify'
    | '/checkout/success'
    | '/api/public/webhooks/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/verify'
    | '/checkout/success'
    | '/api/public/webhooks/checkout'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/verify'
    | '/checkout/success'
    | '/api/public/webhooks/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  VerifyRoute: typeof VerifyRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicWebhooksCheckoutRoute: typeof ApiPublicWebhooksCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/checkout': {
      id: '/api/public/webhooks/checkout'
      path: '/api/public/webhooks/checkout'
      fullPath: '/api/public/webhooks/checkout'
      preLoaderRoute: typeof ApiPublicWebhooksCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  VerifyRoute: VerifyRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicWebhooksCheckoutRoute: ApiPublicWebhooksCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
